yonaskolb/Mint

Sources/MintKit/MintKit.swift
Sources/MintKit/Package.swift

Checkout fresh package each install

---

README.md
Sources/Mint/main.swift
Sources/MintKit/MintKit.swift
Sources/MintKit/Package.swift

Add list command

---

Sources/Mint/main.swift

Add version flag

---

README.md

Add cmdshelf to README

---

Package.resolved
Package.swift
README.md
Sources/Mint/main.swift
Sources/MintKit/Commands/InstallCommand.swift
Sources/MintKit/Commands/ListCommand.swift
Sources/MintKit/Commands/MintCommand.swift
Sources/MintKit/Commands/MintInterface.swift
Sources/MintKit/Commands/PackageCommand.swift
Sources/MintKit/Commands/RunCommand.swift
Sources/MintKit/Commands/UninstallCommand.swift
Sources/MintKit/Commands/UpdateCommand.swift
Sources/MintKit/Mint.swift
Sources/MintKit/MintError.swift
Sources/MintKit/PackagePath.swift
Tests/LinuxMain.swift
Tests/MintTests/MintTests.swift

- replaces Guaka with Swift PM ArgumentParser
- refactored commands 
- moves parsing into MintKit
- resolves #39

Refactored commands

---

README.md

RasterizeXCAssets is a tool for rasterizing SVG files into `.xcassets` assets.
Side note: maybe we should sort the tools lexicographically?

Add RasterizeXCAssets to tools section

---

Sources/MintKit/Commands/PackageCommand.swift
Sources/MintKit/Commands/RunCommand.swift
Sources/MintKit/Mint.swift
Sources/MintKit/MintError.swift
Tests/MintTests/MintTests.swift

Add --silent argument

---

Sources/MintKit/Mint.swift

Link Swift standard libs when installing

---

README.md
Sources/Mint/main.swift
Sources/MintKit/Commands/ListCommand.swift
Sources/MintKit/Commands/MintCommand.swift
Sources/MintKit/Commands/MintInterface.swift
Sources/MintKit/Commands/PackageCommand.swift
Sources/MintKit/Commands/UninstallCommand.swift
Sources/MintKit/Mint.swift

Add MINT_PATH and MINT_INSTALL_PATH envs

---

README.md

Assetizer is a too to create image assets from single image file.

Added  jkmathew/Assetizer to readme

---

Sources/MintKit/Commands/PackageCommand.swift

Replace Swift.print with Mint.standardOutput
Refs
- https://github.com/yonaskolb/Mint/pull/64
- https://github.com/yonaskolb/Mint/pull/72

Fix to support silent option when use via Mintfile

---

.circleci/config.yml
README.md
Sources/MintCLI/Commands/RunCommand.swift
Sources/MintKit/Mint.swift
Tests/Fixtures/SimpleMintfile
Tests/LinuxMain.swift
Tests/MintTests/MintTests.swift
Tests/MintTests/XCTestManifests.swift

Linux support

---

README.md

Both tools add Mint support in latest releases
- [Carting](https://github.com/artemnovichkov/Carting/pull/20)
- [SwiftGen](https://github.com/SwiftGen/SwiftGen/pull/411)

Add SwiftGen and Carting tools to README.md

---

CHANGELOG.md
Sources/MintCLI/MintCLI.swift
Sources/MintKit/Mint.swift
Sources/MintKit/MintError.swift
Sources/MintKit/PackagePath.swift
Sources/MintKit/PackageReference.swift
Sources/MintKit/SwiftPackage.swift
Tests/MintTests/MintTests.swift
Tests/MintTests/PackageTests.swift

Resolves #106 
Resolves #114 
Resolves #86
Resolves #74
- provides finer grained error output
- updates output and error messages
- adds a `Resolving` step to the output

Provide finer grained package errors

---

CHANGELOG.md
Sources/MintKit/PackageReference.swift
Tests/MintTests/PackageTests.swift

Related to #118 
I agree it's not the most elegant way to do it, I accept advices on how to improve it.

Support for external SSH packages

---

README.md

The README says Xcode 9.2 is required, but I think this should say 10.2, right?

Update README Xcode version specification

---

README.md

Hi. We just released new version of SwiftyMocky, adding a CLI tool installed via Mint. Would be nice to show up on the list :)
https://github.com/MakeAWishFoundation/SwiftyMocky

Added SwiftyMocky to the list

---

README.md

Hi! It would be nice to have xcbeautify in the list of compatible packages.

Add xcbeautify to the compatible packages

---

Package.resolved
Sources/MintCLI/Commands/InstallCommand.swift
Sources/MintKit/InputReader.swift
Sources/MintKit/Mint.swift
Sources/MintKit/SwiftPackage.swift
Tests/MintTests/MintTests.swift

Update SwiftCLI and fixes #https://github.com/yonaskolb/Mint/issues/143

Update SwiftCLI and fix options input

---

Sources/MintKit/Mint.swift

This quietens down output a bit
- move `Using \(package.repo) \(package.version) from Mintfile.` to verbose
- move `Running \(packagePath.executable ?? "") \(package.version)..` to verbose
- move `Found \(packageCount) in \(mintFilePath.string)` to verbose
- move `\(packagePath.commandVersion) already installed` in run to verbose (keep for plain install)
- change end of bootstrap to `\(packageCount) up to date` if no packages were installed, otherwise add installed packages count

Tweak output

---

CHANGELOG.md
Sources/MintCLI/Commands/RunCommand.swift
Sources/MintKit/Mint.swift
Sources/MintKit/MintError.swift
Tests/MintTests/MintTests.swift

Add --no-install to mint run

---

CHANGELOG.md
Sources/MintCLI/Commands/WhichCommand.swift
Sources/MintCLI/MintCLI.swift
Sources/MintKit/Mint.swift
Tests/MintTests/MintTests.swift

Fixes #154
Replaces and closes #73

Add which command

---

README.md

I have also opened a PR in the Weaver repo to add Mint installation instructions to their README: https://github.com/scribd/Weaver/pull/143

Added Weaver as a mint compatible package

---

Package.resolved
Package.swift

SwiftCLI v6.0.3 has a partial fix for this issue https://github.com/yonaskolb/Mint/issues/217.
PathKit fix still in progress https://github.com/kylef/PathKit/issues/77

Update SwiftCLI to v6.0.3

---

Package.resolved
Package.swift

Update PathKit to v1.0.1 to fix issue #217.

Update PathKit to v1.0.1
