yonaskolb/Mint

- README.md
- Sources/MintKit/MintKit.swift
Fixes #4 
This moves the mint directory from `/usr/local/mint` to `/usr/local/lib/mint` which should fix the issue with tightened permissions in High Sierra
> Fix permissions

- Sources/MintKit/MintKit.swift
I was getting a pretty mysterious error:
So I opened it in Xcode and attached a breakpoint to Swift errors. Turns out that the git command to get the latest tag will fail instead of giving no output
So this handles that.
> Add a try catch for when a lib has no tags

- README.md
- Sources/Mint/main.swift
This changes
```
$ mint run realm/swiftlint 0.22.0
```
to:
```
$ mint run realm/swiftlint@0.22.0
```
This also removes the guessing of what the second argument is as at it will always be the executable command
> Change version to an @ suffix to the repo

- CHANGELOG.md
- README.md
- Sources/MintKit/MintKit.swift
- latest tag is now retrieved with `git ls-remote --tags` before a clone if no version is specified
- git clone is now shallow
> Change git fetching

- Package.resolved
- Package.swift
- Sources/MintKit/MintKit.swift
Fixes #29
This uses SwiftPM itself to parse versions and sort them. 
Having this dependency paves the way for implementing #17, as well as possibly moving fetching to SwiftPM
> Use SwiftPM to sort tags

- Package.resolved
- Package.swift
- Sources/Mint/main.swift
- Sources/MintKit/MintKit.swift
This replaces ShellOut with SwiftShell. This allows for streaming of stdout and stderror, and easily allows custom contexts, which allows the following features.
- Resolves #35: stream output of run command
- Resolves #3: `--verbose` flag now shows output of cloning and building
- Resolves #5: `MINT=YES` and `RESOURCE_PATH=""` are now passed to the run command. This allows a tool to know if it is being run through mint, and allows us to change the resource path dynamically in the future.
> Stream output

- CHANGELOG.md
- README.md
- Sources/Mint/main.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
Resolves #1 
This allows installing a package globally. At the moment this is behind a `--global` flag, which may change to the default in the future.
There is also an obligatory `uninstall` command
> Global install and uninstall

- Sources/Mint/main.swift
- Sources/MintKit/Commands/Question.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
This is an alternative to #41.
It changes the global installation path from a custom one that need a new `$PATH` entry, to the standard `/usr/local/bin`. The installed file is still symlinked to Mint's own directory.
This greatly simplifies things and keeps Mint out of peoples bash configs.
Mint asks for confirmation before trying to overwrite or remove an existing executable that is not symlinked to mint.
With this method, I'd be more comfortable making Mint install globally by default
> Change global install path from custom to /usr/local/bin

- Sources/MintKit/Commands/ListCommand.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
I changed of the list command to display global version.
When multiple versions are installed in mint, a global installed version is represented by asterisk `*`
```shell
$ mint list
Installed mint packages:
simplepackage
- 2.0.0
- 3.0.0 *
```
> Update the list command for display of global installed versions

- Sources/MintKit/Mint.swift
Fixes #58 🚀 
I have also confirmed that this fixes building of Carthage 0.29.x:
> Parse current OS version as swiftc target

- Sources/MintCLI/Commands/RunCommand.swift
Fix the problem that "🌱  Using \"\(package.repo)\" \"\(package.version)\" from Mintfile." is output even when the silent option is enabled.
Refs
- https://github.com/yonaskolb/Mint/pull/64
- https://github.com/yonaskolb/Mint/pull/72
- https://github.com/yonaskolb/Mint/pull/77
> Fix the timing to adapt silent option

- README.md
When running the Mintfile with version 0.9.0 like stated in the Readme mint exits with 
`fatal: Remote branch 0.9.0 not found in upstream origin
Couldn't clone https://github.com/yonaskolb/xcodegen.git 0.9.0`.
Since there is a newer version of xcodegen around I think it would be a good idea to correct that version.
> Update xcodegen version in Mintfile example

- Sources/MintKit/Mint.swift
```
$ mint install toshi0383/hackscode
🌱  Finding latest version of hackscode
🌱  Resolved latest version of hackscode to 0.2.2
🌱  Cloning https://github.com/toshi0383/hackscode.git 0.2.2...
🌱  Building hackscode with SPM...
🌱  Installing...
🌱  Copying resources for hackscode: Sources/Scripts/xquick.sh ...
An error occurred: Error Domain=NSCocoaErrorDomain Code=4 "The file “xquick.sh” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/f1/drl_8qdj0qs19y07br7q313xr5q2d9/T/mint_554643071.423989/github.com_toshi0383_hackscode/Sources/Scripts/xquick.sh, NSUserStringVariant=(
Copy
), NSDestinationFilePath=/usr/local/lib/mint/packages/github.com_toshi0383_hackscode/build/0.2.2/Sources/Scripts/xquick.sh, NSFilePath=/var/folders/f1/drl_8qdj0qs19y07br7q313xr5q2d9/T/mint_554643071.423989/ …
```
> Fix failing to copy nested resources

- README.md
- Sources/MintCLI/Commands/InstallCommand.swift
- Sources/MintCLI/Commands/ListCommand.swift
- Sources/MintCLI/MintCLI.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
- Tests/MintTests/PackageTests.swift
- Tests/MintTests/XCTestManifests.swift
This renames `global` to `link` in the codebase. User facing changes are
- `MINT_INSTALL_PATH` env -> `MINT_LINK_PATH`
- `--prevent-global` -> `--no-link`
> Rename global to link

- Sources/MintKit/Mint.swift
- Sources/MintKit/MintError.swift
- Tests/MintTests/MintTests.swift
- Fixes #99
- Enables `mint install` to use package lookup by name. So if `realm/swiftlint` is installed then you can do `mint install swiftlint`
> Resolve package references in correct order

- README.md
cmdshelf will be (has been) ported to Rust from Swift.
https://github.com/toshi0383/cmdshelf/pull/78
Thanks a lot for the support! 😄
> Remove cmdshelf from README

- Sources/MintKit/Mint.swift
When fail to initialize SwiftPackage in install command, it just passed `MintError.packageFileNotFound` before.
However, this can happen not only because the file's absence but also invalid `Package.swift` status or other reason related with `Package.swift` faults.
So I think it shouldn't be expressed as Mint's domestic error, should pass the CaptureError or so.
Please condider merging this!
#114
> make it simply pass capture error

- Sources/MintKit/SwiftPackage.swift
as discussed in #129, Mint is not currently compatible with new SPM.
Seems like the new `dump-package` is returning products differently than before, specifically:
- when product is executable, type is 
```javascript
"type": {
"executable": null
}
```
- when product is library, type is
```javascript
"type": {
"library":["static"]
}
```
that's why I'm currently checking the `isExecutable` var in that way.
Unit tests are currently failing (but they were failing anyway) and probably need further investigation.
> make Product compatible with Swift/SPM 5.0

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- Package.resolved
- Package.swift
- Sources/MintKit/Mint.swift
- Sources/MintKit/StringExtensions.swift
- Sources/MintKit/SwiftPackage.swift
This updates to Swift 5 and drops Swift 4.2.
I've had to disable the Linux tests for now as it's failing there with the following error and not sure why yet:
```
<unknown>:0: error: unable to execute command: Killed
<unknown>:0: error: compile command failed due to signal 9 (use -v to see invocation)
```
> Update to Swift 5

- README.md
Though not yet popular, our tool fits in with the other tools.
> Add icon-resizer-swift to the list of mints

- CHANGELOG.md
- README.md
- Sources/MintCLI/Commands/BootstrapCommand.swift
- Sources/MintCLI/Commands/MintFileCommand.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
Solves https://github.com/yonaskolb/Mint/issues/136.
The new flag added is `-l` or `--link`.
Usage:
`mint bootstrap --link`.
For the next major version it may be good to align what is the default behaviour. At the moment:
- `install`: links globally by default.
- `bootstrap`: does not link globally by default.
> Added the option to link the packages of a mintfile globally

- CHANGELOG.md
- Sources/MintKit/PackageReference.swift
- Tests/MintTests/PackageTests.swift
I'm trying to integrate the R.swift project into my Mintfile (https://github.com/mac-cain13/R.swift/issues/593) and I've done so using the shorthand syntax like this:
```
liamnichols/R.swift@ln/build-rule # (using a fork for a bugfix)
```
However upon trying to install via `mint bootstrap` I get the following: 
```
mint bootstrap
🌱  Found 2 packages in Mintfile
🌱  SwiftLint 0.38.0 already installed
🌱  Cloning R ln/build-rule
Cloning into 'liamnichols_R.swift'...
fatal: unable to access 'https://liamnichols/R.swift.git/': Could not resolve host: liamnichols
🌱  Encountered error during "git clone --depth 1 -b ln/build-rule https://liamnichols/R.swift.git liamnichols_R.swift". Use --verbose to see full output
🌱  Couldn't clone https://liamnichols/R.swift.git ln/build-rule
```
After digging …
> Installer cannot resolve gitPath using shortened GitHub repo name if repo has a period in its name

- CHANGELOG.md
- Package.resolved
- Package.swift
- Sources/MintCLI/Commands/BootstrapCommand.swift
- Sources/MintCLI/Commands/InstallCommand.swift
- Sources/MintCLI/Commands/MintFileCommand.swift
- Sources/MintCLI/Commands/PackageCommand.swift
- Sources/MintCLI/Commands/RunCommand.swift
- Sources/MintCLI/Commands/UninstallCommand.swift
This uses the new property wrappers introduced in SwiftCLI 6.0
```swift
@Flag("-s", "--silent", description: "Silences any output from Mint itself")
var silent: Bool
```
> Update to SwiftCLI 6.0

- CHANGELOG.md
- README.md
- Sources/MintCLI/Commands/RunCommand.swift
- Sources/MintKit/Mint.swift
- Tests/MintTests/MintTests.swift
Fixes #145
This allows `mint run` to drop the executable name. It still supports it if specified. With packages with multiple executables it can still be specified, or a new `--executable` argument can be used in case the first arguments passed to the executable matches the executable
All of these work
```
mint run realm/SwiftLint
mint run realm/SwiftLint autocorrect
mint run swiftlint
mint run swiftLint autocorrect
mint run swiftLint swiftlint autocorrect #for backwards compatability
mint run --executable swiftlint realm/SwiftLint autocorrect
```
> Allow mint run to drop the executable name

- README.md
Added xcparse as a Mint compatible package. Unsure if we meet the definition of popular enough for inclusion.
> Add xcparse to Mint compatible packages

- CHANGELOG.md
- Sources/MintKit/Mint.swift
I had issues, when MINT_LINK_PATH contained spaces.
Other similar calls seem to be escaped already.
Tested with the following scheme settings:
> Escape arguments for ls

- CHANGELOG.md
- Sources/MintKit/Cache.swift
- Sources/MintKit/Mint.swift
- Sources/MintKit/MintError.swift
- Tests/Fixtures/ComplexMintfile
- Tests/MintTests/Fixtures.swift
- Tests/MintTests/MintTests.swift
Added fixes to cover the following two scenarios:
1- When a package with the same name is installed from different origins. For example: `yonaskolb/xcodegen` and `acecilia/xcodegen`.
2- When a package produces multiple executables.
The main additions of this PR are:
1. A rewrite of the `list` option.
2. A fix for the `run` option, so it asks for which package to run when multiple origins are detected, instead of just running the first match.
3. A rewrite of the `uninstall` option, which includes the following fix: previously, the name for the symlink to remove was calculated using the passed package name, which could be partial (for example `sample` instead of `samplepackage`), resulting on the symlink not being removed. Also added tests
> Added fixes to better support packages with multiple origins and multiple executables

- CHANGELOG.md
- Sources/MintKit/Mint.swift
- Sources/MintKit/PackageReference.swift
- Tests/MintTests/MintTests.swift
- Tests/MintTests/PackageTests.swift
Previously it was impossible to reference a git SHA because Mint used a shallow clone which doesn't support sha's. This detects such situations and then does a clone and checkout
> Fix installing git SHA version

- CHANGELOG.md
- Sources/MintKit/Mint.swift
When the version cannot be resolved while being offline, this PR will try to find locally installed versions. It will try to use the latest version.
This fixes #164
> Allow running offline without specified version

- README.md
Swift on Linux is not ABI stable in any available 5.x version. There are currently no public plans to introduce ABI stability on Linux.
> Update Linux Swift ABI note in README.md

- CHANGELOG.md
- Sources/MintKit/Mint.swift
- Sources/MintKit/ProcessInfoExtensions.swift
- Tests/MintTests/ProcessInfoExtensionTests.swift
Closes #184 (cc @amine2233)
As identified in the linked PR, hardcoding the target when forming the `swift build` command on macOS has become a limiting factor when supporting Apple Silicon. Thankfully @esteluk already provided a viable work around that preserves some other requirements defined in #58.
I've taken the two suggestions and formed them into a single PR that should hopefully be good to go 🤞
I can confirm that this does the job nicely on Apple Silicon by using Realm's SwiftLint as a test project since your SimplePackage is too simple to throw up any build error in the tests. If it helps I can try and help you to expand that package a bit to reproduce the issue but I'm not sure how important that is.
> Support building for architectures other than x86_64 on macOS (Apple Silicon)

- Sources/MintKit/Mint.swift
- Tests/Fixtures/MintfileWithoutVersion
- Tests/MintTests/Fixtures.swift
- Tests/MintTests/MintTests.swift
When Mintfile does not contain package versions, installing with simple
names such as `mint install xcodegen` fails with "package not found" error.
I'm not sure if Mintfile supports package specification without version though.
> Fix error on trying to install package with name only

- Makefile
Build a universal binary to include arm64 as mentioned in #185 as per https://liamnichols.github.io/2020/08/01/building-swift-packages-as-a-universal-binary.html
> Build universal binary

- CHANGELOG.md
- Sources/MintCLI/Commands/InstallCommand.swift
- Sources/MintKit/Mint.swift
When installing globally, you must enter whether you want to overwrite the package if it is already installed. I added an option to override when using it in CI, as in #182 
I'd like to add a similar option to the `mint bootstrap` command afterwards, if this change is approved.
> Add overwrite option to mint install

- README.md
When someone tries out the commands in the README, old versions might lead to errors that are then attributed to mint.
> Update Example Versions in README

- CHANGELOG.md
- Sources/MintCLI/Commands/BootstrapCommand.swift
- Sources/MintKit/Mint.swift
Added `--overwrite` option to `mint bootstrap` as in #186 .
Resolved #182
> Add overwrite option to mint bootstrap

- .github/workflows/swift.yml
- Sources/MintKit/ProcessInfoExtensions.swift
- Tests/MintTests/ProcessInfoExtensionTests.swift
Resolves #196 
[`ProcessInfo.machineHardwareName`](https://github.com/yonaskolb/Mint/pull/185/files#diff-e90019304d64f8d341431032f67544626424aaa233785b85ba42667c4a69a61dR7) has caused a compile error on Linux platform.
However, it was not called on Linux platform, so I made it only available on macOS platform.
Furthermore, I added the test on Linux which has been missed in #158 .
> Skip Apple Silicon supporting flow on Linux platform.

- Makefile
Fixed issue that swift build output path changed when `--arch arm64 --arch x86_64`was added.
Resolved #194
> Fix Makefile BUILD_PATH

- README.md
- Sources/MintCLI/MintCLI.swift
- Sources/MintKit/Mint.swift
Fixes #188
Fixes #215
This changes `$MINT_PATH` to default to `~/.mint` which means there won't be installation issues on higher protected macOS releases or M1 machines.
It also changes `$MINT_LINK_PATH` to `~/.mint/bin` which means global linking will now also succeed with the downside that `~/.mint/bin` must manually be added to `$PATH` if packages need to be run outside of mint
> Change install path

- README.md
In the main section it says that using `mint run` will run the latest version of a package which is installed. Then the Mintfile section says that you can use `mint run tool-name` which is the same as above and I was worried that it would run the latest version. (so I added note to clarify that the version would be resolved from the Mintfile)
We've got multiple projects over here and are using mint to install / manage package tools on our CI machines.
> Add note about how packages are resolved

- README.md
I removed $ symbols for use the copy button on Github.
> Remove $ symbols.

- Sources/MintKit/Mint.swift
Resolves #250 
I tried to run `mint install` with this fix and succeeded on SwiftLint, SwiftFormat and [SSGH(my original package)](https://github.com/417-72KI/SSGH).
> Avoid test utility module in some packages.

- Sources/MintKit/Mint.swift
After mint 0.17.2 package installation sizes have increased considerably due to https://github.com/yonaskolb/Mint/pull/248
This PR changes things so the only build artifacts that are copied from the build directory are:
- executables
- bundles
- resources
- dylibs
It achieves the same outcome as https://github.com/yonaskolb/Mint/pull/224, but just by copying all bundles. After https://github.com/yonaskolb/Mint/pull/251 test bundles won't be included.
Some package installation sizes before and after this PR:
- SwiftLint: 323 MB -> 39.1 MB
- SwiftGen: 190.9 MB -> 6.3 MB
> Only copy required build artifacts

- Sources/MintKit/Mint.swift
closes #255
The changes in #251 add each executable target as an additional `--product \(executable)` to the `swift build` command. Unfortunately, when multiple products are specified with `--product \(executable)`, `swift build` does not build all of them, only the last one.
`swift build` does not seem to have a way to explicitly specify multiple products to build at once, so instead this PR makes Mint run `swift build` once for each executable product.
> Build executables one by one

- Sources/MintKit/Mint.swift
If user customized `MINT_PATH` and `MINT_LINK_PATH` to paths that contain spaces, the final copy of the binary failed because of missing quotes, this PR fixes that.
> Add quotes when copying result binary
